--[[
Iptables file dumper for Alpine Wall
Copyright (C) 2012 Kaarle Ritvanen
Licensed under the terms of GPL2
]]--


module(..., package.seeall)

local iptfiles = {ip4='iptables', ip6='ip6tables'}

config = {}
setmetatable(config,
	     {__index=function(t, k)
			 t[k] = {}
			 setmetatable(t[k], getmetatable(t))
			 return t[k]
		      end})

function dump()
   for family, tbls in pairs(config) do
      local iptfile = io.output('output/'..iptfiles[family])
      iptfile:write('# '..iptfiles[family]..' generated by awall\n')
      for tbl, chains in pairs(tbls) do
	 iptfile:write('*'..tbl..'\n')
	 for chain, rules in pairs(chains) do
	    iptfile:write(':'..chain..' '..(chain == string.upper(chain) and
					 'DROP' or '-')..' [0:0]\n')
	 end
	 for chain, rules in pairs(chains) do
	    for i, rule in ipairs(rules) do
	       iptfile:write('-A '..chain..' '..rule..'\n')
	    end
	 end
	 iptfile:write('COMMIT\n')
      end
   end
end
